---
title: Scious.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    author: Andrew Agostini
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:title"
    author:
      name: Andrew Agostini
url: http://scious.io
