---
title: Scious.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    author:
      name: Andrew Agostini
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    author: Andrew Agostini
